# train process def
resume: true 
checkpoint_dir: 'checkpoints/CCPD18-affine-res50-stn-2en-CDNv1_1-bf-2'
num_epochs: 50
device: cuda
amp_dtype: bf16
GradScaler_enable: false

dataset:
  name: CCPD_4pBbox_affin_noNormAug_CDN_0size
  csvPath: datasets/CCPD2018/ccpd_base_A.csv
  # datasets/CCPD/CCPD_train.csv
  # datasets/CCPD2018/ccpd_base_A.csv
  batch_size: 16
  n_worker: 10
val_set:
  name: CCPD_4pBbox_0size
  csvPath: datasets/CCPD2018/ccpd_others_5%val.csv
  # datasets/CCPD2018/ccpd_base_B.csv
  # datasets/CCPD2018/ccpd_B+O_test.csv
  # datasets/CCPD2018/ccpd_base_A.csv
  # datasets/CCPD2018/ccpd_others_5%val.csv
  # datasets/CCPD/CCPD_test_sample10.csv.gz
  batch_size: 60
  n_worker: 10
  evaluator:
    name: IoU_LPs_evaluator

model:
  name: ALPR_res50_fm32_stn_2en_CDNv1_1

criterion:
  name: Infer_DenoiseLoss
  infer_cfg:
    k_ce: 1
    k_l1: 5
    k_giou: 2
    n_class: 2
    k_l11: 5
    k_giou1: 2
    k_string: 10
    void_class_idx: 0
    void_class_weight: 0.01
  CDN_cfg:
    k_ce: 1
    k_l1: 5
    k_giou: 2
    k_l11: 5
    k_giou1: 2
    k_string: 10

optim:
  name: Adam
  lr: 1e-5
  betas: [0.9,0.999]
  weight_decay: 0

lr_scheduler:
  # name: LambdaLR
  name: StepLR
  step_size: 20
  gamma: 0.1

logger:
  log_dir: "runs/CCPD18-affine-res50-stn-2en-CDNv1_1-bf-2"
  # tensorboard --logdir=runs